### ISSUE TITLE
Testing with v2.0.0-dev, snippets_m error line 159

### ISSUE THREAD

**Issue by csoutham** [adamfairholm/PyroSnippets#10]
Hi, loving Snippets - you really should charge for it!

I'm getting an error when setting up a snippet:
Line 159 - snippets_m
if(isset($this->snippets->{$snippet->type}->parameters)):

ERROR - Severity: Notice  --> Undefined variable: snippet /httpdocs/addons/shared_addons/modules/snippets/models/snippets_m.php 159
ERROR - Severity: Notice  --> Trying to get property of non-object /httpdocs/addons/shared_addons/modules/snippets/models/snippets_m.php 159

If I completely remove the if statement completely (159-167) I get a $params warning in the logs but the snippet saves fine, I'm guessing it probably doesn't save the image allowed types.

Should say I'm running the latest pull of Snippets from Git and the latest Pro pull from v2.0/develop of Pyro.

**Comment by adamfairholm** [comment]
Thanks Chris - just ran into myself and will push a fix shortly.
