### ISSUE TITLE
Fix for {pyro: tag in setup view

### ISSUE THREAD

**Issue by csoutham** [adamfairholm/PyroSnippets#11]
Hi Adam,
Just a quick fix for the Setup view so that it works fully with the ability in the Pro version to rename the {pyro tag.
I believe this will work just fine in the Community edition too.

Line 30 of the setup index.php view should be changed from:
<td>{pyro:snippet:<?php echo $snippet->slug; ?>}</td>

to:
<td>{<?php echo config_item('tags_trigger'); ?>:snippet:<?php echo $snippet->slug; ?>}</td>

Sorry, I'd put in a pull request if I'd figured that out yet!

**Comment by adamfairholm** [comment]
Good call! I just pushed this to the repo along with some other enhancements. Thanks Chris!

**Comment by csoutham** [comment]
No worries, thank you!
