### ISSUE TITLE
Users with non-admin snippet permissions can access snippet setup

### ISSUE THREAD

**Issue by adamfairholm** [adamfairholm/PyroSnippets#15]

**Comment by fuzenco** [comment]
The simple solution is the "Setup" menu item should be hidden if the user's access right indicates they don't have Admin privileges. The ability to check that on and off is already present. Don't know if that's a conditional that could be wrapped around that Setup menu item.

**Comment by adamfairholm** [comment]
There is - that's what we're doing for PyroStreams, hiding menu items based on the user's permissions level. That works well.
