### ISSUE TITLE
Feature Request: On/Off toggling

### ISSUE THREAD

**Issue by fuzenco** [adamfairholm/PyroSnippets#16]
I wish individual Snippets had an on/off setting. If a client wants to toggle whether a Snippet displays on the front-end, they shouldn't have to delete a snippet for that to happen.

Practical application: Like if they had some type of on-going sales banner which was in a sidebar, but for some reason wanted to pull it for a short time and then site it live again.

**Comment by chadwithuhc** [comment]
I like it. I'd vote for it too.
