### ISSUE TITLE
Fatal error when installing PyroSnippets

### ISSUE THREAD

**Issue by ghost** [adamfairholm/PyroSnippets#29]
When I copy the files of the PyroSnippets module to the directory 'modules' and reload the page 'admin/modules' I get the following error:

Fatal error: Declaration of Module_Snippets::upgrade() must be compatible with that of Module::upgrade() in ~/addons/default/modules/snippets/details.php on line 192

What can I do?

I use version 2.1.5 of PyroCMS.

**Comment by adamfairholm** [comment]
@jeroen-net, 

This is a PHP 5.4 issue - go into details.php and make sure that the function declaration says "upgrade($old_version)". I believe it needs to specifically not have the = null in there. Basically, all its saying is that it needs to match.

Adam

**Comment by edmeehan** [comment]
Same issue but on PHP 5.3.24 (production) ... but I am on the latest PyroCMS Pro - 2.2.1, which I know this latest version was not tested for.

Seemed to work fine on my dev environments 5.3.6 & 5.3.10

I just did your suggested fix and it worked on my production 5.3.24

**Comment by adamfairholm** [comment]
Thanks @edmeehan - I'm going to tag this as 2.4 for use with 2.2.x.

**Comment by ghost** [comment]
Thanks for fixing!
