### ISSUE TITLE
Cannot autoload library

### ISSUE THREAD

**Issue by jzmwebdevelopment** [adamfairholm/PyroSnippets#3]
I get

An Error Was Encountered
Unable to load the requested class: chunks

When using chunks/Chunks in the autoload library

**Comment by adamfairholm** [comment]
What version of PyroCMS are you using? If it is 1.2 or above, you shouldn't need to autoload the Chunks library - it does that through an event.

Adam

**Comment by jzmwebdevelopment** [comment]
```
I am using the new one.  but it is still not loading (have emailed
you)
On 29/07/11 1:37 AM, adamfairholm wrote:

  What version of PyroCMS are you using? If it is 1.2 or above, you shouldn't need to autoload the Chunks library - it does that through an event.
```

Adam

On Jul 27, 2011, at 4:23 PM, jzmwebdevelopment wrote:

```
    I get
```

An Error Was Encountered
Unable to load the requested class: chunks

When using chunks/Chunks in the autoload library

## 

Reply to this email directly or view it on GitHub:
https://github.com/adamfairholm/PyroChunks/issues/3

```
-- 
```



Regards
      Jess McKenzie
          JZM Web DevelopmentJess@jzm.co.nz | 0212133263

```
    
   
   
```

**Comment by adamfairholm** [comment]
I'm not sure what you mean - are you autoloading the Chunks library?

**Comment by jzmwebdevelopment** [comment]
Adam,

No I am not,  I have my folder placed here -> 
http://cl.ly/1I1V2L003t1O0m2n2h33 and when I access my site areas that 
use a chunk are blank and when I click chunks in the admin area I get a 404.

Jess

**Comment by adamfairholm** [comment]
Jess,

Try moving the chunks folder to shared_addons/modules. In 1.3, it won't check the root add-on folder for modules.

Adam

**Comment by jzmwebdevelopment** [comment]
Adam,

Still not working, is there away I can see if its being read maybe an 
echo, what file would be best?

J

**Comment by adamfairholm** [comment]
Do you have any other modules loaded and installed? It should be in the same folder.

You could check the events.php file if you'd like, but I don't think it is in the right place.

Adam

**Comment by jzmwebdevelopment** [comment]
Adam,

Thats fine,  It is located in addons/shared_addons/modules/chucks.

J
