### ISSUE TITLE
500 error for pyro 2.0.dev

### ISSUE THREAD

**Issue by otherjohn** [adamfairholm/PyroSnippets#9]
Install goes fine, but when you navigate to admin/snippets you get a 500 error.

**Comment by csoutham** [comment]
Try installing the latest version from here - seems to work fine when I installed today on 2.0.0-dev apart from the bug I've added a ticket for.
You might need to hit Upgrade for the right SQL.

**Comment by adamfairholm** [comment]
Gospell labs - yes, try the latest version - the bleeding edge on the repo. Upgrading should upgrade your SQL as well. Let me know if this fixes the 500 error.
